### PR TITLE
Upgrade to latest RNV

### PR DESCRIPTION
**Pull request by mihaiblaga89**
Task
- https://github.com/flexn-io/create/issues/193

What has been done:

- [x]  android - compiles and runs
- [x]  ios - compiles and runs
- [x]  androidtv - compiles and runs
- [x]  firetv - compiles and runs
- [x]  web - compiles and runs
- [x]  webos - compiles and runs  in hosted mode
- [x]  tvos - compiles and runs
- [x]  tizen - compiles and runs in hosted mode
- [x]  macos - compiles and runs
- [x] Heavily updated focus engine
- [x] Upgrade to rnv@1.0.0-rc.16
- [x] Lightning needs to be removed
- [x] Icons doesn't work on tvos
- [x] rnv new command tested and works with above platforms
- [x] Test webos, tizen on device
- [x] Move neccesarry overides to plugins repo

**Non blocking issues, observations:**
 - Chromecast not tested
 -  Move new create plugins definitions to plugins repo(Can be done after mergint to main)
 - After running web you initially see Hydration error that's known rnv issue
 - These fonts overrides needs to be part of renative same as ios https://github.com/flexn-io/create/blob/feat/rnv_update/packages/template-starter/appConfigs/base/builds/tvos/RNVApp-tvOS/Info.plist#L36
 - This override had to be added in order androidtv to autostart https://github.com/flexn-io/create/blob/feat/rnv_update/packages/template-starter/renative.json#L321. Has to be checked also from rnv side

### CODE REVIEW

**Comment by pauliusguzas** [comment]
tvos has no icons
image

androidTV jumps down after clicking right on carousels page
https://github.com/flexn-io/create/assets/65670660/2f1df630-e871-467c-8509-6bf9c70147c6

On all tv’s TV drawer remains open after opening home or carousels from TV drawer

Carousels screen is not displayed in full screen on webos and on tizen 
webos_carousel

modal has no background on webos, tizen modal is all black
image
image

focus is lost on carousel page when you go back from details screen on webos and tizen. Not first item in row must be opened in order to reproduce
https://github.com/flexn-io/create/assets/65670660/0ea75aaf-6dd8-4f0c-a88e-baba02b1474f

on webos and tizen devices black blank screen is displayed after splash screen (renative issue?)

no app icon on tvos
image

tizen black screen for few s after clicking on item from carousels
image

"My Modal" title doesn't fit in one line on drawer on webos and tizen sim
image

**Comment by aurimasmi** [comment]
When testing this PR please link with another one in https://github.com/flexn-io/renative/pull/1523

**Comment by GabrieleKaceviciute** [comment]
1.3.0-feat-rnv-update.17
- tizen -> carousels, details, modal screens scrolls up/down
- webos (device) -> black screen after splash screen
- tvos -> no app icon

**Comment by GabrieleKaceviciute** [comment]
1.3.0-feat-rnv-update.19

webos -> Can't scroll up/down carousels page

**Pull request merged**
