### PR TITLE
Fix: Incorrect scroll behavior

### PR DESCRIPTION
**Pull request by aurimasmi**
**PR meant to fix:**
* Issue when horizontal scroll direction is instantly changed to vertical and that was causing bouncing effect on tvos

CleanShot2023-05-26at09 05 22

* When you move from one row to another and there is an element which was partially visible, scrollview was not capable to detect that and align it's scroll position

CleanShot2023-05-26at09 07 38

**Extra:**

If scrollview has been requested particular scroll target and it receives more requests with the same target now any subsequent request is ignored and scrollview is allowed to finish first one. That was causing scroll slowdown reaching the end of target

### CODE REVIEW

**Comment by pauliusguzas** [comment]
https://github.com/flexn-io/create/assets/65670660/54fd4384-0dcc-40f2-90d3-5cf74553362e
1. When 1st row is on 1st packshot and 2nd row is scrolled, going down from first row has some jumping
2. When 1st row is on last packshot, going down from first row major jumping
3. Can't fully focus on last item in row

**Comment by aurimasmi** [comment]
@pauliusguzas how would you expect then 1 and 2 to be working? since focus stick to the left and from row above you focused in the middle so what focus does it trying to stick to the left again

**Comment by aurimasmi** [comment]
Anyway all these comments which you described are not related with PR. Let's keep PR's simple and pointing to the issues it suppose to solve. Can you confirm that those issues which is described in description is resolved?

**Comment by pauliusguzas** [comment]
Yes

**Comment by aurimasmi** [comment]
Thanks, I'll raise PR's against your reported issues

**Pull request merged**
